# Generated by Django 2.0.7 on 2018-08-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin_name', models.CharField(max_length=255)),
                ('eng_name', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('order', models.CharField(max_length=255)),
                ('distribution', models.CharField(choices=[('north', 'north'), ('south', 'south'), ('west', 'west'), ('east', 'east'), ('center', 'center')], max_length=6)),
                ('habitat', models.CharField(choices=[('mountains', 'mountains'), ('open plains', 'open plains'), ('forests', 'forests'), ('rivers and lakes', 'rivers and lakes'), ('the seasides', 'the seasides'), ('countries and hamlets', 'countries and hamlets'), ('urban', 'urban'), ('parks and gardens', 'parks and gardens')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BirdPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=255)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bird_app.Bird')),
            ],
        ),
    ]
